// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// drfDLNMadditivebuild
List drfDLNMadditivebuild(const Eigen::VectorXd R_y, const List R_B_inner_list, const List R_knots_f_list, const List R_knots_w_list, const List R_Sw_list, const List R_SwR_list, const List R_Sf_list, const List R_SfR_list, const Eigen::MatrixXd R_Xrand, const Eigen::MatrixXd R_Xfix, const List R_Zf_list, const Eigen::VectorXd R_Xoffset, const Eigen::VectorXd R_r, Eigen::VectorXd R_alpha_f, double R_log_theta, Eigen::VectorXd R_log_smoothing_f, Eigen::VectorXd R_log_smoothing_w, Eigen::VectorXd R_betaR, Eigen::VectorXd R_betaF, Eigen::VectorXd R_logsmoothing);
RcppExport SEXP _drfDLNMadditive_drfDLNMadditivebuild(SEXP R_ySEXP, SEXP R_B_inner_listSEXP, SEXP R_knots_f_listSEXP, SEXP R_knots_w_listSEXP, SEXP R_Sw_listSEXP, SEXP R_SwR_listSEXP, SEXP R_Sf_listSEXP, SEXP R_SfR_listSEXP, SEXP R_XrandSEXP, SEXP R_XfixSEXP, SEXP R_Zf_listSEXP, SEXP R_XoffsetSEXP, SEXP R_rSEXP, SEXP R_alpha_fSEXP, SEXP R_log_thetaSEXP, SEXP R_log_smoothing_fSEXP, SEXP R_log_smoothing_wSEXP, SEXP R_betaRSEXP, SEXP R_betaFSEXP, SEXP R_logsmoothingSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::VectorXd >::type R_y(R_ySEXP);
    Rcpp::traits::input_parameter< const List >::type R_B_inner_list(R_B_inner_listSEXP);
    Rcpp::traits::input_parameter< const List >::type R_knots_f_list(R_knots_f_listSEXP);
    Rcpp::traits::input_parameter< const List >::type R_knots_w_list(R_knots_w_listSEXP);
    Rcpp::traits::input_parameter< const List >::type R_Sw_list(R_Sw_listSEXP);
    Rcpp::traits::input_parameter< const List >::type R_SwR_list(R_SwR_listSEXP);
    Rcpp::traits::input_parameter< const List >::type R_Sf_list(R_Sf_listSEXP);
    Rcpp::traits::input_parameter< const List >::type R_SfR_list(R_SfR_listSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd >::type R_Xrand(R_XrandSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd >::type R_Xfix(R_XfixSEXP);
    Rcpp::traits::input_parameter< const List >::type R_Zf_list(R_Zf_listSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd >::type R_Xoffset(R_XoffsetSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd >::type R_r(R_rSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type R_alpha_f(R_alpha_fSEXP);
    Rcpp::traits::input_parameter< double >::type R_log_theta(R_log_thetaSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type R_log_smoothing_f(R_log_smoothing_fSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type R_log_smoothing_w(R_log_smoothing_wSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type R_betaR(R_betaRSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type R_betaF(R_betaFSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type R_logsmoothing(R_logsmoothingSEXP);
    rcpp_result_gen = Rcpp::wrap(drfDLNMadditivebuild(R_y, R_B_inner_list, R_knots_f_list, R_knots_w_list, R_Sw_list, R_SwR_list, R_Sf_list, R_SfR_list, R_Xrand, R_Xfix, R_Zf_list, R_Xoffset, R_r, R_alpha_f, R_log_theta, R_log_smoothing_f, R_log_smoothing_w, R_betaR, R_betaF, R_logsmoothing));
    return rcpp_result_gen;
END_RCPP
}
// drfDLNMadditiveopt
List drfDLNMadditiveopt(SEXP ptr, Eigen::VectorXd R_alpha_f, double R_log_theta, Eigen::VectorXd R_log_smoothing_f, Eigen::VectorXd R_log_smoothing_w, Eigen::VectorXd R_betaR, Eigen::VectorXd R_betaF, Eigen::VectorXd R_logsmoothing, int nthreads_derivH, bool verbose);
RcppExport SEXP _drfDLNMadditive_drfDLNMadditiveopt(SEXP ptrSEXP, SEXP R_alpha_fSEXP, SEXP R_log_thetaSEXP, SEXP R_log_smoothing_fSEXP, SEXP R_log_smoothing_wSEXP, SEXP R_betaRSEXP, SEXP R_betaFSEXP, SEXP R_logsmoothingSEXP, SEXP nthreads_derivHSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ptr(ptrSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type R_alpha_f(R_alpha_fSEXP);
    Rcpp::traits::input_parameter< double >::type R_log_theta(R_log_thetaSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type R_log_smoothing_f(R_log_smoothing_fSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type R_log_smoothing_w(R_log_smoothing_wSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type R_betaR(R_betaRSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type R_betaF(R_betaFSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type R_logsmoothing(R_logsmoothingSEXP);
    Rcpp::traits::input_parameter< int >::type nthreads_derivH(nthreads_derivHSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(drfDLNMadditiveopt(ptr, R_alpha_f, R_log_theta, R_log_smoothing_f, R_log_smoothing_w, R_betaR, R_betaF, R_logsmoothing, nthreads_derivH, verbose));
    return rcpp_result_gen;
END_RCPP
}
// drfDLNMadditiveCI
List drfDLNMadditiveCI(SEXP ptr, const int Rci, const int rseed, bool ifeta, bool verbose, Rcpp::Nullable<Rcpp::NumericMatrix> R_he_input);
RcppExport SEXP _drfDLNMadditive_drfDLNMadditiveCI(SEXP ptrSEXP, SEXP RciSEXP, SEXP rseedSEXP, SEXP ifetaSEXP, SEXP verboseSEXP, SEXP R_he_inputSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ptr(ptrSEXP);
    Rcpp::traits::input_parameter< const int >::type Rci(RciSEXP);
    Rcpp::traits::input_parameter< const int >::type rseed(rseedSEXP);
    Rcpp::traits::input_parameter< bool >::type ifeta(ifetaSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericMatrix> >::type R_he_input(R_he_inputSEXP);
    rcpp_result_gen = Rcpp::wrap(drfDLNMadditiveCI(ptr, Rci, rseed, ifeta, verbose, R_he_input));
    return rcpp_result_gen;
END_RCPP
}
// ConditionalAICdrfDLNMadditive
List ConditionalAICdrfDLNMadditive(SEXP ptr);
RcppExport SEXP _drfDLNMadditive_ConditionalAICdrfDLNMadditive(SEXP ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ptr(ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(ConditionalAICdrfDLNMadditive(ptr));
    return rcpp_result_gen;
END_RCPP
}
// NCVdrfDLNMadditive
List NCVdrfDLNMadditive(SEXP ptr, const List nei_list, bool verbose, int nthreads);
RcppExport SEXP _drfDLNMadditive_NCVdrfDLNMadditive(SEXP ptrSEXP, SEXP nei_listSEXP, SEXP verboseSEXP, SEXP nthreadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ptr(ptrSEXP);
    Rcpp::traits::input_parameter< const List >::type nei_list(nei_listSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    Rcpp::traits::input_parameter< int >::type nthreads(nthreadsSEXP);
    rcpp_result_gen = Rcpp::wrap(NCVdrfDLNMadditive(ptr, nei_list, verbose, nthreads));
    return rcpp_result_gen;
END_RCPP
}
// BsplinevecCon1st
Eigen::VectorXd BsplinevecCon1st(double x, const Eigen::VectorXd& t, int p, Eigen::MatrixXd Z);
RcppExport SEXP _drfDLNMadditive_BsplinevecCon1st(SEXP xSEXP, SEXP tSEXP, SEXP pSEXP, SEXP ZSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type t(tSEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type Z(ZSEXP);
    rcpp_result_gen = Rcpp::wrap(BsplinevecCon1st(x, t, p, Z));
    return rcpp_result_gen;
END_RCPP
}
// BsplinevecCon2nd
Eigen::VectorXd BsplinevecCon2nd(double x, const Eigen::VectorXd& t, int p, Eigen::MatrixXd Z);
RcppExport SEXP _drfDLNMadditive_BsplinevecCon2nd(SEXP xSEXP, SEXP tSEXP, SEXP pSEXP, SEXP ZSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type t(tSEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type Z(ZSEXP);
    rcpp_result_gen = Rcpp::wrap(BsplinevecCon2nd(x, t, p, Z));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_drfDLNMadditive_drfDLNMadditivebuild", (DL_FUNC) &_drfDLNMadditive_drfDLNMadditivebuild, 20},
    {"_drfDLNMadditive_drfDLNMadditiveopt", (DL_FUNC) &_drfDLNMadditive_drfDLNMadditiveopt, 10},
    {"_drfDLNMadditive_drfDLNMadditiveCI", (DL_FUNC) &_drfDLNMadditive_drfDLNMadditiveCI, 6},
    {"_drfDLNMadditive_ConditionalAICdrfDLNMadditive", (DL_FUNC) &_drfDLNMadditive_ConditionalAICdrfDLNMadditive, 1},
    {"_drfDLNMadditive_NCVdrfDLNMadditive", (DL_FUNC) &_drfDLNMadditive_NCVdrfDLNMadditive, 4},
    {"_drfDLNMadditive_BsplinevecCon1st", (DL_FUNC) &_drfDLNMadditive_BsplinevecCon1st, 4},
    {"_drfDLNMadditive_BsplinevecCon2nd", (DL_FUNC) &_drfDLNMadditive_BsplinevecCon2nd, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_drfDLNMadditive(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
