# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

drfDLNMadditivebuild <- function(R_y, R_B_inner_list, R_knots_f_list, R_knots_w_list, R_Sw_list, R_SwR_list, R_Sf_list, R_SfR_list, R_Xrand, R_Xfix, R_Zf_list, R_Xoffset, R_r, R_alpha_f, R_log_theta, R_log_smoothing_f, R_log_smoothing_w, R_betaR, R_betaF, R_logsmoothing) {
    .Call(`_drfDLNMadditive_drfDLNMadditivebuild`, R_y, R_B_inner_list, R_knots_f_list, R_knots_w_list, R_Sw_list, R_SwR_list, R_Sf_list, R_SfR_list, R_Xrand, R_Xfix, R_Zf_list, R_Xoffset, R_r, R_alpha_f, R_log_theta, R_log_smoothing_f, R_log_smoothing_w, R_betaR, R_betaF, R_logsmoothing)
}

drfDLNMadditiveopt <- function(ptr, R_alpha_f, R_log_theta, R_log_smoothing_f, R_log_smoothing_w, R_betaR, R_betaF, R_logsmoothing, nthreads_derivH, verbose) {
    .Call(`_drfDLNMadditive_drfDLNMadditiveopt`, ptr, R_alpha_f, R_log_theta, R_log_smoothing_f, R_log_smoothing_w, R_betaR, R_betaF, R_logsmoothing, nthreads_derivH, verbose)
}

drfDLNMadditiveCI <- function(ptr, Rci, rseed, ifeta, verbose, R_he_input = NULL) {
    .Call(`_drfDLNMadditive_drfDLNMadditiveCI`, ptr, Rci, rseed, ifeta, verbose, R_he_input)
}

ConditionalAICdrfDLNMadditive <- function(ptr) {
    .Call(`_drfDLNMadditive_ConditionalAICdrfDLNMadditive`, ptr)
}

NCVdrfDLNMadditive <- function(ptr, nei_list, verbose = FALSE, nthreads = 1L) {
    .Call(`_drfDLNMadditive_NCVdrfDLNMadditive`, ptr, nei_list, verbose, nthreads)
}

BsplinevecCon1st <- function(x, t, p, Z) {
    .Call(`_drfDLNMadditive_BsplinevecCon1st`, x, t, p, Z)
}

BsplinevecCon2nd <- function(x, t, p, Z) {
    .Call(`_drfDLNMadditive_BsplinevecCon2nd`, x, t, p, Z)
}

